1. Data Cleaning

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
df = pd.read_excel(r'C:\Users\23163\Desktop\eclsk_c.xlsx')    # 导入数据, 路径等下改一下就行

In [7]:
df.head(10)

,CHILDID,S1_ID,GENDER,WKWHITE,WKSESL,RIRT,MIRT,S2KPUPRI,P1EXPECT,P1FIRKDG,...,P1DISABL,F5SPECS,C5R4RSCL,C6R4RSCL,C5R4MSCL,C6R4MSCL,avg_RIRT,avg_MIRT,avg_SES,avg_apprchT1
0,0001002C,1,0,1,1.56,67.160,51.685,1,5,1,...,0,0,185.22,192.70,124.61,152.24,51.085000,40.61000,1.485,3.08000
1,0001010C,1,0,1,1.41,35.010,29.535,1,6,1,...,0,0,149.05,165.66,110.49,134.90,51.085000,40.61000,1.485,3.08000
2,0002003C,2,1,1,-2.93,49.460,44.815,1,6,1,...,0,0,142.18,141.02,115.59,133.67,47.376875,35.18375,-0.470,2.81125
3,0002004C,2,0,1,0.54,44.625,34.250,1,4,1,...,0,0,130.39,164.54,107.17,141.27,47.376875,35.18375,-0.470,2.81125
4,0002008C,2,0,1,0.15,33.705,22.110,1,6,1,...,0,0,109.04,144.37,70.11,80.16,47.376875,35.18375,-0.470,2.81125
5,0002011C,2,1,1,-0.19,30.000,30.045,1,3,1,...,0,0,114.14,159.64,104.92,130.05,47.376875,35.18375,-0.470,2.81125
6,0002018C,2,0,1,-0.23,43.035,36.185,1,3,1,...,0,0,128.90,149.07,116.75,132.85,47.376875,35.18375,-0.470,2.81125
7,0002019C,2,1,1,-0.12,39.740,35.005,1,4,0,...,0,0,147.36,147.71,124.62,140.66,47.376875,35.18375,-0.470,2.81125
8,0002022C,2,0,1,-0.55,103.395,48.850,1,6,0,...,0,0,169.74,190.39,117.31,155.59,47.376875,35.18375,-0.470,2.81125
9,0002024C,2,0,1,-0.43,35.055,30.210,1,6,1,...,0,0,106.51,138.20,84.64,120.62,47.376875,35.18375,-0.470,2.81125

In [8]:
df.shape #查看数据形状 几行几列

(7362, 41)

In [9]:
df.info() #数据结构

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7362 entries, 0 to 7361
Data columns (total 41 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CHILDID       7362 non-null   object
 1   S1_ID         7362 non-null   int64
 2   GENDER        7362 non-null   int64
 3   WKWHITE       7362 non-null   int64
 4   WKSESL        7362 non-null   float64
 5   RIRT          7362 non-null   float64
 6   MIRT          7362 non-null   float64
 7   S2KPUPRI      7362 non-null   int64
 8   P1EXPECT      7362 non-null   int64
 9   P1FIRKDG      7362 non-null   int64
 10  P1AGEENT      7362 non-null   int64
 11  apprchT1      7362 non-null   float64
 12  P1HSEVER      7362 non-null   int64
 13  chg14         7362 non-null   int64
 14  P1FSTAMP      7362 non-null   int64
 15  S2KMINOR      7362 non-null   int64
 16  ONEPARENT     7362 non-null   int64
 17  STEPPARENT    7362 non-null   int64
 18  P1NUMSIB      7362 non-null   int64
 19  P1HMAFB       7362 non-null   int64
 20  WKCAREPK      7362 non-null   int64
 21  P1EARLY       7362 non-null   int64
 22  wt_ounces     7362 non-null   int64
 23  C1FMOTOR      7362 non-null   int64
 24  C1GMOTOR      7362 non-null   int64
 25  P1HSCALE      7362 non-null   int64
 26  P1SADLON      7362 non-null   float64
 27  P1IMPULS      7362 non-null   float64
 28  P1ATTENI      7362 non-null   int64
 29  P1SOLVE       7362 non-null   int64
 30  P1PRONOU      7362 non-null   int64
 31  P1DISABL      7362 non-null   int64
 32  F5SPECS       7362 non-null   int64
 33  C5R4RSCL      7362 non-null   float64
 34  C6R4RSCL      7362 non-null   float64
 35  C5R4MSCL      7362 non-null   float64
 36  C6R4MSCL      7362 non-null   float64
 37  avg_RIRT      7362 non-null   float64
 38  avg_MIRT      7362 non-null   float64
 39  avg_SES       7362 non-null   float64
 40  avg_apprchT1  7362 non-null   float64
dtypes: float64(14), int64(26), object(1)
memory usage: 2.3+ MB

In [11]:
df.describe () #查看数据的描述性统计信息 数值型

,S1_ID,GENDER,WKWHITE,WKSESL,RIRT,MIRT,S2KPUPRI,P1EXPECT,P1FIRKDG,P1AGEENT,...,P1DISABL,F5SPECS,C5R4RSCL,C6R4RSCL,C5R4MSCL,C6R4MSCL,avg_RIRT,avg_MIRT,avg_SES,avg_apprchT1
count,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,...,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000,7362.000000
mean,840.229965,0.496740,0.750475,0.166585,42.177973,33.346371,0.782260,4.102961,0.966585,65.753464,...,0.127819,0.058272,131.654169,154.424618,102.867131,127.071318,42.177973,33.346371,0.166585,3.086888
std,780.681336,0.500023,0.432767,0.761409,11.520661,10.086620,0.412738,1.033599,0.179729,4.158645,...,0.333910,0.234273,26.324064,24.538564,23.659927,23.366519,5.956643,5.465706,0.514270,0.309375
min,1.000000,0.000000,0.000000,-4.750000,23.165000,11.850000,0.000000,1.000000,0.000000,54.000000,...,0.000000,0.000000,51.610000,66.270000,41.740000,50.860000,27.908333,16.062500,-2.215000,1.500000
25%,334.000000,0.000000,1.000000,-0.380000,35.330000,26.100000,1.000000,4.000000,1.000000,63.000000,...,0.000000,0.000000,111.160000,140.162500,86.792500,113.725000,38.292083,29.616667,-0.210536,2.898667
50%,665.000000,0.000000,1.000000,0.060000,40.080000,32.055000,1.000000,4.000000,1.000000,66.000000,...,0.000000,0.000000,130.100000,156.315000,104.190000,130.930000,41.382857,33.196842,0.152967,3.083750
75%,1024.000000,1.000000,1.000000,0.660000,45.943750,38.651250,1.000000,5.000000,1.000000,69.000000,...,0.000000,0.000000,149.657500,171.657500,119.835000,143.470000,45.111562,36.808846,0.507436,3.292500
max,3116.000000,1.000000,1.000000,2.750000,139.355000,98.990000,1.000000,6.000000,1.000000,79.000000,...,1.000000,1.000000,200.750000,203.220000,166.250000,170.660000,79.980000,66.075000,2.500000,4.000000

In [12]:
df.columns #变量名

Index(['CHILDID', 'S1_ID', 'GENDER', 'WKWHITE', 'WKSESL', 'RIRT', 'MIRT',
       'S2KPUPRI', 'P1EXPECT', 'P1FIRKDG', 'P1AGEENT', 'apprchT1', 'P1HSEVER',
       'chg14', 'P1FSTAMP', 'S2KMINOR', 'ONEPARENT', 'STEPPARENT', 'P1NUMSIB',
       'P1HMAFB', 'WKCAREPK', 'P1EARLY', 'wt_ounces', 'C1FMOTOR', 'C1GMOTOR',
       'P1HSCALE', 'P1SADLON', 'P1IMPULS', 'P1ATTENI', 'P1SOLVE', 'P1PRONOU',
       'P1DISABL', 'F5SPECS', 'C5R4RSCL', 'C6R4RSCL', 'C5R4MSCL', 'C6R4MSCL',
       'avg_RIRT', 'avg_MIRT', 'avg_SES', 'avg_apprchT1'],
      dtype='object')

In [17]:
df.CHILDID #查看其中一列

0       0001002C
1       0001010C
2       0002003C
3       0002004C
4       0002008C
          ...
7357    3115021C
7358    3115025C
7359    3116001C
7360    3116019C
7361    3116024C
Name: CHILDID, Length: 7362, dtype: object

In [13]:
col = df.columns.values

In [14]:
df.columns = [x.strip() for x in col] #除去列名里的空格，万一有的话

In [16]:
df.columns

Index(['CHILDID', 'S1_ID', 'GENDER', 'WKWHITE', 'WKSESL', 'RIRT', 'MIRT',
       'S2KPUPRI', 'P1EXPECT', 'P1FIRKDG', 'P1AGEENT', 'apprchT1', 'P1HSEVER',
       'chg14', 'P1FSTAMP', 'S2KMINOR', 'ONEPARENT', 'STEPPARENT', 'P1NUMSIB',
       'P1HMAFB', 'WKCAREPK', 'P1EARLY', 'wt_ounces', 'C1FMOTOR', 'C1GMOTOR',
       'P1HSCALE', 'P1SADLON', 'P1IMPULS', 'P1ATTENI', 'P1SOLVE', 'P1PRONOU',
       'P1DISABL', 'F5SPECS', 'C5R4RSCL', 'C6R4RSCL', 'C5R4MSCL', 'C6R4MSCL',
       'avg_RIRT', 'avg_MIRT', 'avg_SES', 'avg_apprchT1'],
      dtype='object')

In [19]:
df.duplicated() #返回布尔型数据，告诉重复值的位置

0       False
1       False
2       False
3       False
4       False
        ...
7357    False
7358    False
7359    False
7360    False
7361    False
Length: 7362, dtype: bool

In [20]:
df[df.duplicated()] #这个数据是清洗过的 所以查看重复值的时候发现是没有的 数据是干净的

Empty DataFrame
Columns: [CHILDID, S1_ID, GENDER, WKWHITE, WKSESL, RIRT, MIRT, S2KPUPRI, P1EXPECT, P1FIRKDG, P1AGEENT, apprchT1, P1HSEVER, chg14, P1FSTAMP, S2KMINOR, ONEPARENT, STEPPARENT, P1NUMSIB, P1HMAFB, WKCAREPK, P1EARLY, wt_ounces, C1FMOTOR, C1GMOTOR, P1HSCALE, P1SADLON, P1IMPULS, P1ATTENI, P1SOLVE, P1PRONOU, P1DISABL, F5SPECS, C5R4RSCL, C6R4RSCL, C5R4MSCL, C6R4MSCL, avg_RIRT, avg_MIRT, avg_SES, avg_apprchT1]
Index: []

[0 rows x 41 columns]

In [22]:
df.duplicated().sum() #所以是0个

0

In [24]:
df.drop_duplicates() #删去重复值

,CHILDID,S1_ID,GENDER,WKWHITE,WKSESL,RIRT,MIRT,S2KPUPRI,P1EXPECT,P1FIRKDG,...,P1DISABL,F5SPECS,C5R4RSCL,C6R4RSCL,C5R4MSCL,C6R4MSCL,avg_RIRT,avg_MIRT,avg_SES,avg_apprchT1
0,0001002C,1,0,1,1.56,67.160,51.685,1,5,1,...,0,0,185.22,192.70,124.61,152.24,51.085000,40.610000,1.485000,3.080000
1,0001010C,1,0,1,1.41,35.010,29.535,1,6,1,...,0,0,149.05,165.66,110.49,134.90,51.085000,40.610000,1.485000,3.080000
2,0002003C,2,1,1,-2.93,49.460,44.815,1,6,1,...,0,0,142.18,141.02,115.59,133.67,47.376875,35.183750,-0.470000,2.811250
3,0002004C,2,0,1,0.54,44.625,34.250,1,4,1,...,0,0,130.39,164.54,107.17,141.27,47.376875,35.183750,-0.470000,2.811250
4,0002008C,2,0,1,0.15,33.705,22.110,1,6,1,...,0,0,109.04,144.37,70.11,80.16,47.376875,35.183750,-0.470000,2.811250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7357,3115021C,3115,0,1,0.60,40.845,31.035,1,4,1,...,0,0,141.02,146.77,104.14,123.81,40.685714,32.752143,-0.065714,3.095714
7358,3115025C,3115,1,1,-0.79,31.880,18.310,1,2,1,...,0,0,104.67,109.29,69.28,110.19,40.685714,32.752143,-0.065714,3.095714
7359,3116001C,3116,1,0,0.02,33.195,25.010,1,4,1,...,0,0,105.24,144.82,91.16,118.31,30.228333,21.631667,-0.516667,2.500000
7360,3116019C,3116,0,1,-0.81,30.050,23.990,1,2,1,...,0,0,126.20,128.91,82.09,117.81,30.228333,21.631667,-0.516667,2.500000
7361,3116024C,3116,1,1,-0.76,27.440,15.895,1,6,1,...,0,0,72.79,104.48,69.49,88.53,30.228333,21.631667,-0.516667,2.500000

In [26]:
df.shape[0] #这里因为没有重复值 所以个数没有减少

7362

In [28]:
df.index = range(df.shape[0])   #因为删去一些数据之后 我们要更新他的index比如说第5个数被删了 那么这个index空出来了 后面要补上去 这一步相当于更新index

In [29]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
S1_ID,7362.0,840.229965,780.681336,1.000000,334.000000,665.000000,1024.000000,3116.000
GENDER,7362.0,0.496740,0.500023,0.000000,0.000000,0.000000,1.000000,1.000
WKWHITE,7362.0,0.750475,0.432767,0.000000,1.000000,1.000000,1.000000,1.000
WKSESL,7362.0,0.166585,0.761409,-4.750000,-0.380000,0.060000,0.660000,2.750
RIRT,7362.0,42.177973,11.520661,23.165000,35.330000,40.080000,45.943750,139.355
MIRT,7362.0,33.346371,10.086620,11.850000,26.100000,32.055000,38.651250,98.990
S2KPUPRI,7362.0,0.782260,0.412738,0.000000,1.000000,1.000000,1.000000,1.000
P1EXPECT,7362.0,4.102961,1.033599,1.000000,4.000000,4.000000,5.000000,6.000
P1FIRKDG,7362.0,0.966585,0.179729,0.000000,1.000000,1.000000,1.000000,1.000
P1AGEENT,7362.0,65.753464,4.158645,54.000000,63.000000,66.000000,69.000000,79.000
apprchT1,7362.0,3.086888,0.640896,1.000000,2.670000,3.170000,3.670000,4.000
P1HSEVER,7362.0,0.124015,0.329621,0.000000,0.000000,0.000000,0.000000,1.000
chg14,7362.0,0.055963,0.229866,0.000000,0.000000,0.000000,0.000000,1.000
P1FSTAMP,7362.0,0.126596,0.332542,0.000000,0.000000,0.000000,0.000000,1.000
S2KMINOR,7362.0,2.347732,1.445463,1.000000,1.000000,2.000000,3.000000,5.000
ONEPARENT,7362.0,0.171828,0.377257,0.000000,0.000000,0.000000,0.000000,1.000
STEPPARENT,7362.0,0.057050,0.231953,0.000000,0.000000,0.000000,0.000000,1.000
P1NUMSIB,7362.0,1.452730,1.077367,0.000000,1.000000,1.000000,2.000000,10.000
P1HMAFB,7362.0,24.767183,5.407193,12.000000,20.000000,25.000000,29.000000,45.000
WKCAREPK,7362.0,0.841212,0.365503,0.000000,1.000000,1.000000,1.000000,1.000
P1EARLY,7362.0,4.282939,11.886707,0.000000,0.000000,0.000000,0.000000,112.000
wt_ounces,7362.0,119.499864,20.514045,17.000000,107.000000,120.000000,133.000000,214.000
C1FMOTOR,7362.0,6.097120,1.944466,0.000000,5.000000,6.000000,8.000000,9.000
C1GMOTOR,7362.0,6.450829,1.773428,0.000000,6.000000,7.000000,8.000000,8.000
P1HSCALE,7362.0,1.601467,0.766319,1.000000,1.000000,1.000000,2.000000,5.000
P1SADLON,7362.0,1.534027,0.377064,1.000000,1.250000,1.500000,1.750000,4.000
P1IMPULS,7362.0,1.904170,0.643237,1.000000,1.500000,2.000000,2.000000,4.000
P1ATTENI,7362.0,1.839582,0.620217,1.000000,1.000000,2.000000,2.000000,4.000
P1SOLVE,7362.0,1.699402,0.575478,1.000000,1.000000,2.000000,2.000000,4.000
P1PRONOU,7362.0,1.726026,0.632670,1.000000,1.000000,2.000000,2.000000,4.000
P1DISABL,7362.0,0.127819,0.333910,0.000000,0.000000,0.000000,0.000000,1.000
F5SPECS,7362.0,0.058272,0.234273,0.000000,0.000000,0.000000,0.000000,1.000
C5R4RSCL,7362.0,131.654169,26.324064,51.610000,111.160000,130.100000,149.657500,200.750
C6R4RSCL,7362.0,154.424618,24.538564,66.270000,140.162500,156.315000,171.657500,203.220
C5R4MSCL,7362.0,102.867131,23.659927,41.740000,86.792500,104.190000,119.835000,166.250
C6R4MSCL,7362.0,127.071318,23.366519,50.860000,113.725000,130.930000,143.470000,170.660
avg_RIRT,7362.0,42.177973,5.956643,27.908333,38.292083,41.382857,45.111562,79.980
avg_MIRT,7362.0,33.346371,5.465706,16.062500,29.616667,33.196842,36.808846,66.075
avg_SES,7362.0,0.166585,0.514270,-2.215000,-0.210536,0.152967,0.507436,2.500
avg_apprchT1,7362.0,3.086888,0.309375,1.500000,2.898667,3.083750,3.292500,4.000

In [37]:
sta = (df['WKSESL']-df['WKSESL'].mean())/df['WKSESL'].std() #超出三倍标准差 找到具体的数据 需要单独考虑一下 是不是有问题 建模的时候通常删掉

In [35]:
sta.abs()>3

0       False
1       False
2        True
3       False
4       False
        ...
7357    False
7358    False
7359    False
7360    False
7361    False
Name: WKSESL, Length: 7362, dtype: bool

In [36]:
df[sta.abs()>3]

,CHILDID,S1_ID,GENDER,WKWHITE,WKSESL,RIRT,MIRT,S2KPUPRI,P1EXPECT,P1FIRKDG,...,P1DISABL,F5SPECS,C5R4RSCL,C6R4RSCL,C5R4MSCL,C6R4MSCL,avg_RIRT,avg_MIRT,avg_SES,avg_apprchT1
2,0002003C,2,1,1,-2.93,49.460,44.815,1,6,1,...,0,0,142.18,141.02,115.59,133.67,47.376875,35.183750,-0.470000,2.811250
197,0036010C,36,0,0,-2.76,31.860,20.185,1,6,1,...,0,0,86.64,103.33,74.85,89.32,33.750000,26.652000,-0.608000,3.300000
523,0080021C,80,0,1,-3.61,38.455,38.740,1,4,1,...,0,0,115.53,162.74,110.73,142.72,38.946667,29.876667,-0.390000,3.055000
748,0132012C,132,1,1,2.46,48.320,39.910,1,4,1,...,1,0,159.31,185.66,130.97,158.17,42.870833,35.094444,1.097778,3.248333
935,0170006C,170,0,1,-4.18,28.555,16.210,1,4,1,...,0,0,85.59,124.56,52.24,61.74,32.162500,21.532500,-2.215000,2.450000
1311,0247020C,247,1,1,2.47,43.635,42.795,1,6,1,...,1,0,148.06,155.24,154.07,160.50,45.458571,41.436786,1.187143,3.071429
1433,0265002C,265,1,0,2.47,43.145,38.660,1,5,1,...,0,0,110.46,168.14,118.01,158.17,38.968750,33.756250,0.726667,2.888333
1479,0271013C,271,1,1,2.55,42.155,35.950,1,6,1,...,0,0,150.20,159.89,130.06,153.92,41.717273,39.410909,1.060000,3.182727
1507,0279004C,279,1,0,2.57,83.940,33.490,0,6,1,...,0,0,163.56,161.76,122.97,152.02,75.060000,46.375000,1.864444,3.315556
1508,0279006C,279,1,0,2.64,76.115,55.155,0,6,1,...,0,0,148.00,182.85,156.73,166.93,75.060000,46.375000,1.864444,3.315556
1727,0314008C,314,1,1,2.56,43.845,34.625,0,4,1,...,0,0,135.90,164.46,104.90,122.18,51.804737,40.764474,0.964211,3.060526
3058,0507018C,507,1,1,2.51,38.230,34.065,1,6,1,...,0,0,136.41,165.68,118.63,131.70,46.837000,40.901000,1.341000,3.184000
3137,0520007C,520,1,0,-3.61,28.490,27.620,1,2,1,...,0,0,97.17,121.16,88.82,116.47,27.908333,23.789167,-0.966667,2.961667
3164,0524011C,524,0,0,-4.18,27.425,16.075,0,2,1,...,0,0,71.28,95.60,64.27,63.52,30.949167,21.066667,-1.528333,2.583333
3428,0606013C,606,0,1,2.52,49.720,59.460,1,5,1,...,0,0,165.05,193.16,166.25,170.66,50.219231,39.412308,0.953077,3.358462
3662,0663002C,663,1,1,2.53,48.280,29.555,0,6,1,...,0,0,128.37,148.60,107.94,131.60,55.493333,39.993333,0.873333,2.888333
3856,0710015C,710,1,0,-2.33,42.450,30.695,1,4,1,...,0,0,158.76,166.23,121.39,155.33,38.322500,23.726250,-0.960000,2.707500
3941,0731010C,731,0,0,-4.47,39.520,32.960,1,3,1,...,0,0,88.82,165.28,73.31,121.50,34.495000,24.551111,-1.165556,2.500000
4128,0758013C,758,1,0,-3.61,37.425,31.765,1,3,1,...,0,0,126.11,157.74,89.05,129.01,32.254583,24.131667,-0.768333,1.985833
4154,0761010C,761,1,0,-3.27,24.700,21.945,1,4,1,...,0,0,61.66,70.01,62.86,77.05,31.658125,22.385938,-0.633750,2.672500
4191,0764024C,764,0,0,-4.75,38.400,22.595,1,4,1,...,0,0,115.28,133.39,70.28,87.64,38.789000,26.834667,-0.814000,2.722000
4203,0765019C,765,0,0,-3.27,31.660,24.720,1,3,1,...,0,0,95.10,122.87,75.46,102.08,34.081786,25.035714,-0.842857,3.165000
4214,0766016C,766,0,0,-4.18,47.570,34.925,1,3,1,...,0,0,141.56,141.44,94.43,123.37,38.192308,25.831154,-0.856923,3.230769
4260,0776009C,776,0,1,-3.72,39.745,27.035,1,2,0,...,0,0,90.39,128.61,76.37,93.10,39.259643,29.994286,-0.210714,3.083571
4298,0782004C,782,0,1,2.50,58.540,40.635,0,4,1,...,0,0,164.54,196.92,137.95,157.81,58.540000,40.635000,2.500000,3.330000
4323,0790014C,790,1,1,2.67,104.350,41.595,1,5,1,...,1,0,160.21,192.26,130.24,160.50,49.114500,38.852500,0.546000,3.283000
4395,0808013C,808,1,0,-2.66,26.725,17.960,1,4,1,...,1,1,125.98,144.61,83.08,86.00,45.597692,32.849615,-0.060000,3.179231
4456,0815011C,815,0,0,-2.65,26.590,19.540,1,4,1,...,0,0,106.83,126.05,68.05,94.12,34.544167,29.145833,-0.587500,2.750000
4610,0836021C,836,0,0,-4.47,41.750,30.760,1,4,1,...,0,0,127.16,144.36,119.56,123.43,40.528333,29.827222,-0.961111,3.278889
4659,0842020C,842,1,0,-2.65,41.040,29.065,1,5,1,...,0,0,137.78,156.06,74.57,105.88,35.355000,25.100000,-1.970000,2.165000
4667,0845020C,845,1,0,-2.17,28.230,20.345,1,1,1,...,1,0,67.28,96.26,68.44,84.37,33.554000,22.915500,-0.637000,3.116000
4686,0850001C,850,0,0,2.56,57.075,42.760,0,6,1,...,0,0,168.09,192.94,125.79,142.53,43.770882,38.785294,0.354706,2.843529
4951,0887012C,887,0,0,2.69,46.615,27.925,0,6,1,...,0,0,167.64,191.38,81.39,113.96,42.280000,36.775000,0.824000,3.283000
4966,0891019C,891,0,1,-2.66,46.850,33.690,1,4,1,...,0,0,128.14,166.53,86.51,94.28,40.284000,32.227000,-1.058000,3.666000
5163,0945011C,945,1,1,2.56,53.735,42.990,0,4,1,...,0,0,181.59,194.07,151.60,169.89,53.021667,40.665833,1.450000,2.473333
5266,0969009C,969,0,1,2.51,44.265,35.360,0,6,1,...,0,0,147.28,156.97,101.06,127.51,43.771000,32.785500,0.732000,2.451000
5336,1000022C,1000,0,1,2.47,37.260,24.930,1,4,1,...,0,0,147.03,166.07,120.22,151.94,43.090667,35.234000,0.929333,3.136000
5522,1024020C,1024,1,1,2.67,52.090,46.300,0,6,1,...,0,0,141.07,167.42,132.51,153.94,59.551786,49.554286,1.330000,2.954286
5525,1024023C,1024,0,1,2.75,55.975,47.125,0,6,1,...,0,0,125.62,132.64,101.75,128.35,59.551786,49.554286,1.330000,2.954286
5583,1041018C,1041,1,0,-4.47,32.770,27.115,1,2,1,...,0,0,106.77,131.53,75.77,118.96,31.741250,22.921875,-0.970000,2.783750
5637,1053011C,1053,1,1,-4.47,35.005,23.340,1,2,1,...,1,1,82.75,105.48,68.16,93.62,44.482273,36.163182,-0.393636,2.720909
5718,1083003C,1083,0,1,2.61,37.410,23.575,1,6,1,...,0,0,140.36,162.75,104.01,126.43,44.120714,31.735714,1.247143,2.780000
6046,1165015C,1165,1,1,2.51,42.650,73.920,0,5,1,...,0,0,163.86,177.12,151.41,160.70,56.500789,49.774737,1.416316,3.421053
6108,1185016C,1185,0,0,-3.61,30.140,19.060,1,5,1,...,0,0,89.37,105.57,62.57,75.32,36.893182,25.016818,-0.605455,2.912727
6517,1275007C,1275,0,0,-2.46,36.880,34.890,1,4,1,...,0,0,147.40,157.38,104.19,126.18,36.052692,28.278462,-0.501538,3.063846
6621,2057010C,2057,1,1,2.50,41.405,43.745,0,4,1,...,0,0,163.52,183.20,139.90,165.13,41.405000,43.745000,2.500000,4.000000
7014,3041007C,3041,1,1,-4.47,32.985,28.995,1,3,0,...,0,0,145.46,151.53,98.45,119.19,35.775625,34.198750,-0.457500,3.540000
7031,3044012C,3044,0,1,2.62,34.245,26.060,1,5,1,...,0,0,151.27,164.89,94.84,126.15,39.522667,34.260000,0.942667,3.360667
7308,3105009C,3105,1,0,-4.47,50.205,38.875,1,2,0,...,1,0,116.17,126.49,88.93,129.33,56.870000,48.628125,0.038750,3.478750
7336,3110002C,3110,0,0,-2.35,26.775,22.890,1,5,1,...,0,0,105.24,153.19,127.11,116.59,31.293333,25.264167,-0.791667,2.528333

In [38]:
delindex = pd.concat([df[sta.abs()>3]]).index

In [40]:
df.drop(delindex, inplace = True)

In [41]:
df.shape #异常值已经删除了

(7312, 41)

In [43]:
df.index = range(df.shape[0])

In [44]:
df

,CHILDID,S1_ID,GENDER,WKWHITE,WKSESL,RIRT,MIRT,S2KPUPRI,P1EXPECT,P1FIRKDG,...,P1DISABL,F5SPECS,C5R4RSCL,C6R4RSCL,C5R4MSCL,C6R4MSCL,avg_RIRT,avg_MIRT,avg_SES,avg_apprchT1
0,0001002C,1,0,1,1.56,67.160,51.685,1,5,1,...,0,0,185.22,192.70,124.61,152.24,51.085000,40.610000,1.485000,3.080000
1,0001010C,1,0,1,1.41,35.010,29.535,1,6,1,...,0,0,149.05,165.66,110.49,134.90,51.085000,40.610000,1.485000,3.080000
2,0002004C,2,0,1,0.54,44.625,34.250,1,4,1,...,0,0,130.39,164.54,107.17,141.27,47.376875,35.183750,-0.470000,2.811250
3,0002008C,2,0,1,0.15,33.705,22.110,1,6,1,...,0,0,109.04,144.37,70.11,80.16,47.376875,35.183750,-0.470000,2.811250
4,0002011C,2,1,1,-0.19,30.000,30.045,1,3,1,...,0,0,114.14,159.64,104.92,130.05,47.376875,35.183750,-0.470000,2.811250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7307,3115021C,3115,0,1,0.60,40.845,31.035,1,4,1,...,0,0,141.02,146.77,104.14,123.81,40.685714,32.752143,-0.065714,3.095714
7308,3115025C,3115,1,1,-0.79,31.880,18.310,1,2,1,...,0,0,104.67,109.29,69.28,110.19,40.685714,32.752143,-0.065714,3.095714
7309,3116001C,3116,1,0,0.02,33.195,25.010,1,4,1,...,0,0,105.24,144.82,91.16,118.31,30.228333,21.631667,-0.516667,2.500000
7310,3116019C,3116,0,1,-0.81,30.050,23.990,1,2,1,...,0,0,126.20,128.91,82.09,117.81,30.228333,21.631667,-0.516667,2.500000
7311,3116024C,3116,1,1,-0.76,27.440,15.895,1,6,1,...,0,0,72.79,104.48,69.49,88.53,30.228333,21.631667,-0.516667,2.500000

In [45]:
df.isnull()

,CHILDID,S1_ID,GENDER,WKWHITE,WKSESL,RIRT,MIRT,S2KPUPRI,P1EXPECT,P1FIRKDG,...,P1DISABL,F5SPECS,C5R4RSCL,C6R4RSCL,C5R4MSCL,C6R4MSCL,avg_RIRT,avg_MIRT,avg_SES,avg_apprchT1
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7307,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7308,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7309,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7310,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7311,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [46]:
df.isnull().sum() #这里就是没有缺失值

CHILDID         0
S1_ID           0
GENDER          0
WKWHITE         0
WKSESL          0
RIRT            0
MIRT            0
S2KPUPRI        0
P1EXPECT        0
P1FIRKDG        0
P1AGEENT        0
apprchT1        0
P1HSEVER        0
chg14           0
P1FSTAMP        0
S2KMINOR        0
ONEPARENT       0
STEPPARENT      0
P1NUMSIB        0
P1HMAFB         0
WKCAREPK        0
P1EARLY         0
wt_ounces       0
C1FMOTOR        0
C1GMOTOR        0
P1HSCALE        0
P1SADLON        0
P1IMPULS        0
P1ATTENI        0
P1SOLVE         0
P1PRONOU        0
P1DISABL        0
F5SPECS         0
C5R4RSCL        0
C6R4RSCL        0
C5R4MSCL        0
C6R4MSCL        0
avg_RIRT        0
avg_MIRT        0
avg_SES         0
avg_apprchT1    0
dtype: int64

In [48]:
df[df.P1FSTAMP.isnull()] #查看具体缺失值的行

Empty DataFrame
Columns: [CHILDID, S1_ID, GENDER, WKWHITE, WKSESL, RIRT, MIRT, S2KPUPRI, P1EXPECT, P1FIRKDG, P1AGEENT, apprchT1, P1HSEVER, chg14, P1FSTAMP, S2KMINOR, ONEPARENT, STEPPARENT, P1NUMSIB, P1HMAFB, WKCAREPK, P1EARLY, wt_ounces, C1FMOTOR, C1GMOTOR, P1HSCALE, P1SADLON, P1IMPULS, P1ATTENI, P1SOLVE, P1PRONOU, P1DISABL, F5SPECS, C5R4RSCL, C6R4RSCL, C5R4MSCL, C6R4MSCL, avg_RIRT, avg_MIRT, avg_SES, avg_apprchT1]
Index: []

[0 rows x 41 columns]

In [50]:
df['P1FSTAMP'].fillna(round(df['P1FSTAMP'].mean(),0), inplace=True) #均值填补就行 如果是数值类数据的话 其他的话到时候看到再解决